[package]
name = "hemtt-paa"
version = "0.1.0"
authors = ["Brett <brett@mayson.io>"]
edition = "2018"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
byteorder = "1.4"
image = "0.24.3"
texpresso = "2.0.1"
libc = "0.2"
