[package]
name = "hemtt-pbo"
version = "0.1.0"
authors = ["Brett <brett@mayson.io>"]
edition = "2018"

[dependencies]
hemtt-io = { path = "../hemtt-io" }

log = "0.4"
byteorder = "1.4"
sha-1 = "0.10"
indexmap = "1.9.1"
